server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8002
    #context-path: /ymw-admin
# DataSource
spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/goods_yard?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
      username: root
      password: admin
      filters: stat,wall,log4j,config
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
  # spring boot admin
  application:
    name: ymw-admin
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: ${spring.application.name}	# 注册到consul的服务名称
  boot:
    admin:
      client:
        url: "http://localhost:8000"
# 开放健康检查接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
# 打印sql
#mybatis:
## spring boot集成mybatis的方式打印sql
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#日志的方式打印sql
logging:
  level:
    com.ymw.admin.dao: DEBUG
mybatis-plus:
  mapper-locations: classpath*:**/sqlmap/*.xml,classpath*:**/sqlmap/*/*.xml
  type-aliases-package: com.ymw.*.model
  global-config:
    refresh-mapper: true
    db-column-underline: true
  configuration:
    map-underscore-to-camel-case: true

# 文件路径
file:
  img: D://file//img//
  doc: D://file//doc//
  video: D://file//video//
  audio: D://file//audio//
  other: D://file//other//

#Matser的ip地址  
redis:
  hostName: localhost
#端口号  
  port: 6379
#如果有密码  
  password: 123456
#客户端超时时间单位是毫秒 默认是2000 
  timeout: 100000
#最大空闲数  
  maxIdle: 300
#连接池的最大数据库连接数。设为0表示无限制,如果是jedis 2.4以后用redis.maxTotal  
#redis.maxActive=600  
#控制一个pool可分配多少个jedis实例,用来替换上面的redis.maxActive,如果是jedis 2.4以后用该属性  
  maxTotal: 1000
#最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。  
  maxWaitMillis: 1000
#连接的最小空闲时间 默认1800000毫秒(30分钟)  
  minEvictableIdleTimeMillis: 300000
#每次释放连接的最大数目,默认3  
  numTestsPerEvictionRun: 1024
#逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1  
  timeBetweenEvictionRunsMillis: 30000
#是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个  
  testOnBorrow: true
#在空闲时检查有效性, 默认false  
  testWhileIdle: true